# Uncomment this line to define a global platform for your project
# platform :ios, ‘8.0’

target 'TravelPass' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TravelPass
  pod 'MFSideMenu'

  target 'TravelPassTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TravelPassUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
